-- DEPRECATED — Do not run. The app no longer sends these extra columns.
-- Extra sale fields (discount_type, batch_id, subtotal_aud, …) are kept in localStorage only.
-- See supabase-bridge.js → SALES_DB_COLUMNS for the exact insert allowlist.
